In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot  as plt
import seaborn as sns
from pandas_profiling import ProfileReport
from sklearn.preprocessing import OneHotEncoder,LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
import pickle
import os
%matplotlib inline

In [2]:
df = pd.read_csv('adult.csv')

In [3]:
df.head()

age          workclass  fnlwgt   education  education-num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loss  hours-per-week         country  salary  
0          2174             0              40   United-States   <=50K  
1             0             0              13   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40   United-States   <=50K  
4             0             0              40            Cuba   <=50K

In [4]:
df.shape

(32561, 15)

In [5]:
col_for_encoding = ['workclass','marital-status','race','sex']

In [6]:
df['race'].unique()

array([' White', ' Black', ' Asian-Pac-Islander', ' Amer-Indian-Eskimo',
       ' Other'], dtype=object)

In [7]:
df['workclass'].unique()

array([' State-gov', ' Self-emp-not-inc', ' Private', ' Federal-gov',
       ' Local-gov', ' ?', ' Self-emp-inc', ' Without-pay',
       ' Never-worked'], dtype=object)

In [8]:
df['marital-status'].unique()

array([' Never-married', ' Married-civ-spouse', ' Divorced',
       ' Married-spouse-absent', ' Separated', ' Married-AF-spouse',
       ' Widowed'], dtype=object)

In [9]:
df.salary.unique()

array([' <=50K', ' >50K'], dtype=object)

In [10]:
df.salary.value_counts()

 <=50K    24720
 >50K      7841
Name: salary, dtype: int64

In [11]:
type(df.salary[0])

str

In [12]:
df.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
country           0
salary            0
dtype: int64

In [13]:
df.occupation.value_counts()

 Prof-specialty       4140
 Craft-repair         4099
 Exec-managerial      4066
 Adm-clerical         3770
 Sales                3650
 Other-service        3295
 Machine-op-inspct    2002
 ?                    1843
 Transport-moving     1597
 Handlers-cleaners    1370
 Farming-fishing       994
 Tech-support          928
 Protective-serv       649
 Priv-house-serv       149
 Armed-Forces            9
Name: occupation, dtype: int64

In [14]:
pf = ProfileReport(df)

In [15]:
pf.to_widgets()

Summarize dataset:   0%|          | 0/28 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render widgets:   0%|          | 0/1 [00:00<?, ?it/s]

In [16]:
df['salary'] = df['salary'].map({' >50K':1,' <=50K':0})

In [17]:
df.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
country           0
salary            0
dtype: int64

In [18]:
df.head(40)

age          workclass  fnlwgt      education  education-num  \
0    39          State-gov   77516      Bachelors             13   
1    50   Self-emp-not-inc   83311      Bachelors             13   
2    38            Private  215646        HS-grad              9   
3    53            Private  234721           11th              7   
4    28            Private  338409      Bachelors             13   
5    37            Private  284582        Masters             14   
6    49            Private  160187            9th              5   
7    52   Self-emp-not-inc  209642        HS-grad              9   
8    31            Private   45781        Masters             14   
9    42            Private  159449      Bachelors             13   
10   37            Private  280464   Some-college             10   
11   30          State-gov  141297      Bachelors             13   
12   23            Private  122272      Bachelors             13   
13   32            Private  205019     Assoc-acdm             12   
14   40            Private  121772      Assoc-voc             11   
15   34            Private  245487        7th-8th              4   
16   25   Self-emp-not-inc  176756        HS-grad              9   
17   32            Private  186824        HS-grad              9   
18   38            Private   28887           11th              7   
19   43   Self-emp-not-inc  292175        Masters             14   
20   40            Private  193524      Doctorate             16   
21   54            Private  302146        HS-grad              9   
22   35        Federal-gov   76845            9th              5   
23   43            Private  117037           11th              7   
24   59            Private  109015        HS-grad              9   
25   56          Local-gov  216851      Bachelors             13   
26   19            Private  168294        HS-grad              9   
27   54                  ?  180211   Some-college             10   
28   39            Private  367260        HS-grad              9   
29   49            Private  193366        HS-grad              9   
30   23          Local-gov  190709     Assoc-acdm             12   
31   20            Private  266015   Some-college             10   
32   45            Private  386940      Bachelors             13   
33   30        Federal-gov   59951   Some-college             10   
34   22          State-gov  311512   Some-college             10   
35   48            Private  242406           11th              7   
36   21            Private  197200   Some-college             10   
37   19            Private  544091        HS-grad              9   
38   31            Private   84154   Some-college             10   
39   48   Self-emp-not-inc  265477     Assoc-acdm             12   

            marital-status          occupation    relationship  \
0            Never-married        Adm-clerical   Not-in-family   
1       Married-civ-spouse     Exec-managerial         Husband   
2                 Divorced   Handlers-cleaners   Not-in-family   
3       Married-civ-spouse   Handlers-cleaners         Husband   
4       Married-civ-spouse      Prof-specialty            Wife   
5       Married-civ-spouse     Exec-managerial            Wife   
6    Married-spouse-absent       Other-service   Not-in-family   
7       Married-civ-spouse     Exec-managerial         Husband   
8            Never-married      Prof-specialty   Not-in-family   
9       Married-civ-spouse     Exec-managerial         Husband   
10      Married-civ-spouse     Exec-managerial         Husband   
11      Married-civ-spouse      Prof-specialty         Husband   
12           Never-married        Adm-clerical       Own-child   
13           Never-married               Sales   Not-in-family   
14      Married-civ-spouse        Craft-repair         Husband   
15      Married-civ-spouse    Transport-moving         Husband   
16           Never-married     Farming-fishing       Own-child   
17           Never-married 

In [19]:
df.salary.value_counts()

0    24720
1     7841
Name: salary, dtype: int64

In [20]:
df.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'capital-gain', 'capital-loss', 'hours-per-week', 'country', 'salary'],
      dtype='object')

In [21]:
df['net_capital_gain_or_loss'] = df['capital-gain']-df['capital-loss']

In [22]:
df.race.value_counts()

 White                 27816
 Black                  3124
 Asian-Pac-Islander     1039
 Amer-Indian-Eskimo      311
 Other                   271
Name: race, dtype: int64

In [23]:
col = ['country','occupation','education','capital-gain','capital-loss','relationship']
df =df.drop(col,axis=1)

In [24]:
df.head(40)

age          workclass  fnlwgt  education-num          marital-status  \
0    39          State-gov   77516             13           Never-married   
1    50   Self-emp-not-inc   83311             13      Married-civ-spouse   
2    38            Private  215646              9                Divorced   
3    53            Private  234721              7      Married-civ-spouse   
4    28            Private  338409             13      Married-civ-spouse   
5    37            Private  284582             14      Married-civ-spouse   
6    49            Private  160187              5   Married-spouse-absent   
7    52   Self-emp-not-inc  209642              9      Married-civ-spouse   
8    31            Private   45781             14           Never-married   
9    42            Private  159449             13      Married-civ-spouse   
10   37            Private  280464             10      Married-civ-spouse   
11   30          State-gov  141297             13      Married-civ-spouse   
12   23            Private  122272             13           Never-married   
13   32            Private  205019             12           Never-married   
14   40            Private  121772             11      Married-civ-spouse   
15   34            Private  245487              4      Married-civ-spouse   
16   25   Self-emp-not-inc  176756              9           Never-married   
17   32            Private  186824              9           Never-married   
18   38            Private   28887              7      Married-civ-spouse   
19   43   Self-emp-not-inc  292175             14                Divorced   
20   40            Private  193524             16      Married-civ-spouse   
21   54            Private  302146              9               Separated   
22   35        Federal-gov   76845              5      Married-civ-spouse   
23   43            Private  117037              7      Married-civ-spouse   
24   59            Private  109015              9                Divorced   
25   56          Local-gov  216851             13      Married-civ-spouse   
26   19            Private  168294              9           Never-married   
27   54                  ?  180211             10      Married-civ-spouse   
28   39            Private  367260              9                Divorced   
29   49            Private  193366              9      Married-civ-spouse   
30   23          Local-gov  190709             12           Never-married   
31   20            Private  266015             10           Never-married   
32   45            Private  386940             13                Divorced   
33   30        Federal-gov   59951             10      Married-civ-spouse   
34   22          State-gov  311512             10      Married-civ-spouse   
35   48            Private  242406              7           Never-married   
36   21            Private  197200             10           Never-married   
37   19            Private  544091              9       Married-AF-spouse   
38   31            Private   84154             10      Married-civ-spouse   
39   48   Self-emp-not-inc  265477             12      Married-civ-spouse   

                   race      sex  hours-per-week  salary  \
0                 White     Male              40       0   
1                 White     Male              13       0   
2                 White     Male              40       0   
3                 Black     Male              40       0   
4                 Black   Female              40       0   
5                 White   Female              40       0   
6                 Black   Female              16       0   
7                 White     Male              45       1   
8                 White   Female              50       1   
9                 White     Male              40       1   
10                Black     Male              80       1   
11   Asian-Pac-Islander     Male              40       1   
12                White   Female              30       0   
13    

In [25]:
#delete duplicate rows.
df = df.drop_duplicates()

In [26]:
df.shape

(32476, 10)

In [27]:
df

age          workclass  fnlwgt  education-num       marital-status  \
0       39          State-gov   77516             13        Never-married   
1       50   Self-emp-not-inc   83311             13   Married-civ-spouse   
2       38            Private  215646              9             Divorced   
3       53            Private  234721              7   Married-civ-spouse   
4       28            Private  338409             13   Married-civ-spouse   
...    ...                ...     ...            ...                  ...   
32556   27            Private  257302             12   Married-civ-spouse   
32557   40            Private  154374              9   Married-civ-spouse   
32558   58            Private  151910              9              Widowed   
32559   22            Private  201490              9        Never-married   
32560   52       Self-emp-inc  287927              9   Married-civ-spouse   

         race      sex  hours-per-week  salary  net_capital_gain_or_loss  
0       White     Male              40       0                      2174  
1       White     Male              13       0                         0  
2       White     Male              40       0                         0  
3       Black     Male              40       0                         0  
4       Black   Female              40       0                         0  
...       ...      ...             ...     ...                       ...  
32556   White   Female              38       0                         0  
32557   White     Male              40       1                         0  
32558   White   Female              40       0                         0  
32559   White     Male              20       0                         0  
32560   White   Female              40       1                     15024  

[32476 rows x 10 columns]

In [28]:
col_for_encoding = ['workclass','marital-status','race','sex']

In [29]:
lbencoder = LabelEncoder()
for i in col_for_encoding:
    df[i]=lbencoder.fit_transform(df[i])

In [30]:
df.head(40)

age  workclass  fnlwgt  education-num  marital-status  race  sex  \
0    39          7   77516             13               4     4    1   
1    50          6   83311             13               2     4    1   
2    38          4  215646              9               0     4    1   
3    53          4  234721              7               2     2    1   
4    28          4  338409             13               2     2    0   
5    37          4  284582             14               2     4    0   
6    49          4  160187              5               3     2    0   
7    52          6  209642              9               2     4    1   
8    31          4   45781             14               4     4    0   
9    42          4  159449             13               2     4    1   
10   37          4  280464             10               2     2    1   
11   30          7  141297             13               2     1    1   
12   23          4  122272             13               4     4    0   
13   32          4  205019             12               4     2    1   
14   40          4  121772             11               2     1    1   
15   34          4  245487              4               2     0    1   
16   25          6  176756              9               4     4    1   
17   32          4  186824              9               4     4    1   
18   38          4   28887              7               2     4    1   
19   43          6  292175             14               0     4    0   
20   40          4  193524             16               2     4    1   
21   54          4  302146              9               5     2    0   
22   35          1   76845              5               2     2    1   
23   43          4  117037              7               2     4    1   
24   59          4  109015              9               0     4    0   
25   56          2  216851             13               2     4    1   
26   19          4  168294              9               4     4    1   
27   54          0  180211             10               2     1    1   
28   39          4  367260              9               0     4    1   
29   49          4  193366              9               2     4    1   
30   23          2  190709             12               4     4    1   
31   20          4  266015             10               4     2    1   
32   45          4  386940             13               0     4    1   
33   30          1   59951             10               2     4    1   
34   22          7  311512             10               2     2    1   
35   48          4  242406              7               4     4    1   
36   21          4  197200             10               4     4    1   
37   19          4  544091              9               1     4    0   
38   31          4   84154             10               2     4    1   
39   48          6  265477             12               2     4    1   

    hours-per-week  salary  net_capital_gain_or_loss  
0               40       0                      2174  
1               13       0                         0  
2               40       0                         0  
3               40       0                         0  
4               40       0                         0  
5               40       0                         0  
6               16       0                         0  
7               45       1                         0  
8               50       1                     14084  
9               40       1                      5178  
10              80       1                         0  
11              40       1                         0  
12              30       0                         0  
13              50       0                         0  
14              40       1                         0  
15              45       0                         0  
16              35       0                         0  
17              40       0                         0  
18    

In [31]:
df['workclass'].unique()

array([7, 6, 4, 1, 2, 0, 5, 8, 3])

In [32]:
df['race'].unique()

array([4, 2, 1, 0, 3])

In [33]:
df['sex'].unique()

array([1, 0])

In [36]:
df['marital-status'].unique()

array([4, 2, 0, 3, 5, 1, 6])

In [37]:
y = df.salary
df_final= df.drop('salary',axis=1)

In [38]:
df_final.head()

age  workclass  fnlwgt  education-num  marital-status  race  sex  \
0   39          7   77516             13               4     4    1   
1   50          6   83311             13               2     4    1   
2   38          4  215646              9               0     4    1   
3   53          4  234721              7               2     2    1   
4   28          4  338409             13               2     2    0   

   hours-per-week  net_capital_gain_or_loss  
0              40                      2174  
1              13                         0  
2              40                         0  
3              40                         0  
4              40                         0

In [39]:
df_col = df_final.columns

In [40]:
object= StandardScaler()
scale =pd.DataFrame(object.fit_transform(df_final),columns=df_col)

In [41]:
scale.head()

age  workclass    fnlwgt  education-num  marital-status      race  \
0  0.029400   2.148205 -1.062993       1.134104        0.922243  0.394012   
1  0.836010   1.462189 -1.008125       1.134104       -0.405127  0.394012   
2 -0.043928   0.090156  0.244849      -0.420527       -1.732497  0.394012   
3  1.055995   0.090156  0.425454      -1.197843       -0.405127 -1.960562   
4 -0.777210   0.090156  1.407192       1.134104       -0.405127 -1.960562   

        sex  hours-per-week  net_capital_gain_or_loss  
0  0.703175       -0.036006                  0.159207  
1  0.703175       -2.221539                 -0.133848  
2  0.703175       -0.036006                 -0.133848  
3  0.703175       -0.036006                 -0.133848  
4 -1.422121       -0.036006                 -0.133848

In [42]:
X = scale

In [43]:
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.3,random_state=1)
X_train

age  workclass    fnlwgt  education-num  marital-status      race  \
15245  0.762682   0.090156 -1.418334      -1.975159       -0.405127  0.394012   
18707  2.229246  -1.281876  0.071031      -0.420527       -0.405127  0.394012   
1572  -1.070523   0.090156  0.079174      -0.031870        0.922243  0.394012   
20845  1.642621   1.462189  0.331369       0.745446        0.258558  0.394012   
25743 -0.703882   0.090156 -1.067794      -1.197843        1.585928  0.394012   
...         ...        ...       ...            ...             ...       ...   
17289  2.742544  -2.653909 -0.994453      -0.031870        2.249613  0.394012   
5192   1.789277   0.090156  0.807146       1.134104       -0.405127  0.394012   
12172  1.569292   0.090156 -0.111118      -0.420527       -1.732497 -1.960562   
235    1.495964   2.148205  0.747174      -0.420527       -0.405127  0.394012   
29733  1.715949   0.090156 -0.394567      -1.586501       -0.405127 -1.960562   

            sex  hours-per-week  net_capital_gain_or_loss  
15245  0.703175       -0.036006                 -0.133848  
18707  0.703175       -0.440735                 -0.133848  
1572   0.703175       -0.845463                 -0.133848  
20845 -1.422121        4.011276                 -0.133848  
25743 -1.422121        0.125885                 -0.505088  
...         ...             ...                       ...  
17289 -1.422121       -0.036006                 -0.133848  
5192   0.703175       -0.440735                 -0.368400  
12172 -1.422121       -0.197898                 -0.133848  
235    0.703175       -0.036006                 -0.133848  
29733  0.703175       -0.036006                 -0.133848  

[22733 rows x 9 columns]

In [44]:
model = LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression()

In [45]:
pred =model.predict(X_test)

In [130]:
model_score = dict()
print(model.score(X_train,y_train))
model_score['LogisticRegression']=model.score(X_test,y_test)

0.8174020146922976


In [131]:
confusion_matrix(y_test,pred)

array([[6973,  427],
       [1350,  993]], dtype=int64)

In [48]:
pwd
C:\Users\DELL\Desktop\project

SyntaxError: unexpected character after line continuation character (<ipython-input-48-5e2e6fb95825>, line 2)

In [132]:
cd ..

C:\Users\DELL\Desktop


In [133]:
cd Desktop/project/

[WinError 3] The system cannot find the path specified: 'Desktop/project/'
C:\Users\DELL\Desktop


In [134]:
file= 'finalized_model.sav'
pickle.dump(model,open(file,'wb'))

In [135]:
loaded_model = pickle.load(open(file, 'rb'))

### 

In [136]:
l=[39,7,77516,13,4,4,1,40,2174]

In [137]:
xinput = object.fit_transform(np.array(l).reshape(-1,1))

In [138]:
#ypred = loaded_model.predict(xinput)
xinput

array([[-0.36355931],
       [-0.36487723],
       [ 2.8273398 ],
       [-0.36463012],
       [-0.36500079],
       [-0.36500079],
       [-0.36512434],
       [-0.36351812],
       [-0.27562909]])

In [139]:
xinput[2][0]

2.8273398004586734

In [140]:
l1=[]
for i in range(9):
    l1.append(xinput[i][0])

In [141]:
ypred = loaded_model.predict([l1])

In [142]:
ypred

array([0], dtype=int64)

In [143]:
dict_sex ={'Male':1,'Female':0}
dict_race ={'Black' :2, 'White' :4 , 'Asian-Pac-Islander' : 1  ,  'Amer-Indian-Eskimo' : 0 ,'Other' :3}
dict_workclass ={'State-gov':7, 'Self-emp-not-inc':6, 'Private':4, 'Federal-gov':1,'Local-gov':2, ' ?':0, 'Self-emp-inc':5, 'Without-pay':8,'Never-worked':3}
dict_marital = {'Never-married':4, 'Married-civ-spouse':2, 'Divorced':0,'Married-spouse-absent':3, 'Separated':5, 'Married-AF-spouse':1,'Widowed':6}


In [144]:
l = [39, 77516, 13, 40, 2174, dict_workclass['State-gov'], dict_marital['Never-married'], dict_race['White'], dict_sex['Male']]



In [145]:
xinput = object.fit_transform(np.array(l).reshape(-1,1))

l1 = []
for i in range(9):
    l1.append(xinput[i][0])

In [146]:
 prediction = loaded_model.predict([l1])

In [147]:
prediction

array([0], dtype=int64)

In [148]:
output =""
if prediction == 0:
    output = "<50k"
else:
    output = '>50k'

In [149]:
print(output)

<50k


In [150]:
from sklearn.tree import DecisionTreeClassifier

In [151]:
tree = DecisionTreeClassifier(max_depth=5,max_leaf_nodes=5,)
tree.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=5, max_leaf_nodes=5)

In [152]:
print(tree.score(X_train,y_train))
model_score['DecisionTreeClassifier']=tree.score(X_test,y_test)

0.8291470549421546


In [153]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

In [154]:
rf = RandomForestClassifier()


In [155]:
param ={'criterion':['gini','entropy'],'max_depth':np.arange(1,10)}

In [156]:
gd = GridSearchCV(estimator=rf,param_grid=param)

In [157]:
gd.fit(X_train,y_train)

GridSearchCV(estimator=RandomForestClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': array([1, 2, 3, 4, 5, 6, 7, 8, 9])})

In [158]:
gd.best_estimator_

RandomForestClassifier(max_depth=9)

In [159]:
rf = RandomForestClassifier(max_depth=9)
rf.fit(X_train,y_train)

RandomForestClassifier(max_depth=9)

In [160]:
print(rf.score(X_train,y_train))
model_score['RandomForestClassifier']=rf.score(X_test,y_test)

0.8642502089473453


In [161]:
from sklearn.neighbors import KNeighborsClassifier

In [162]:
kn = KNeighborsClassifier()

In [163]:
param ={'weights' : ['uniform', 'distance'],'n_neighbors':np.arange(1,10),'p':[1,2]}

In [164]:
gd = GridSearchCV(estimator=kn,param_grid=param)

In [165]:
gd.fit(X_train,y_train)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
                         'p': [1, 2], 'weights': ['uniform', 'distance']})

In [166]:
gd.best_estimator_

KNeighborsClassifier(n_neighbors=9, p=1)

In [167]:
kn = KNeighborsClassifier(n_neighbors=9, p=1)

In [168]:
kn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=9, p=1)

In [169]:
print(kn.score(X_train,y_train))
model_score['KNeighborsClassifier']=kn.score(X_test,y_test)

0.8638103197994106


In [170]:
model_score

{'LogisticRegression': 0.8176126449758802,
 'DecisionTreeClassifier': 0.8282869752642923,
 'RandomForestClassifier': 0.8538437852817408,
 'KNeighborsClassifier': 0.8301344555065175}

In [176]:
def selec_best_model(model_score):
    ms= list(model_score.values())
    ms_name= list(model_score.keys())
    best_score = max(ms)
    position = ms.index(best_score)
    
    return ms_name[position]
    

In [177]:
best_model = selec_best_model(model_score)

In [178]:
best_model

'RandomForestClassifier'